### PR TITLE
Upgrade to CakePHP 4.5 for UBI8, UBI9 and PHP 7.4+

### LINKED ISSUE #136: cakephp-ex-80 does not work in OpenShift 4.12.3
I did those steps based on the 'ansible-tests' repo:

```
$ oc process -f https://raw.githubusercontent.com/sclorg/cakephp-ex/master/openshift/templates/cakephp.json -p PHP_VERSION=8.0-ubi8 -p NAMESPACE=rhscl-ci-testing
$ oc logs cakephp-example-1-build
time="2023-02-15T13:19:29Z" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
I0215 13:19:29.812960       1 defaults.go:112] Defaulting to storage driver "overlay" with options [mountopt=metacopy=on].
Caching blobs under "/var/cache/blobs".
Trying to pull registry.redhat.io/ubi8/php-80@sha256:484b11613bc0c2fb7acf2faf14f2c2ffd1f923e40a19dc211639124331b66567...
Getting image source signatures
Copying blob sha256:afc4b116bfb27b1bfbd63ba1fdb2f729952ec13237c9e4d6bc39064ce05eec39
Copying blob sha256:1eb1cc491a1bd8e2827ef1c90d2253d5aca4348cc5642ec2206c85dfd20a22e1
Copying blob sha256:ea0a20a2c44861ba5e4cd80a32868b6f8265cd3ee81310d4d493a1b50d1c0d8c
Copying blob sha256:1168d1ba798e705e625266c2b2e6f9f5c6842088359ee056d63aed2eeffa00b5
Copying config sha256:c34769fff406c30c83c2178d496832375a30bf1aba5e930158df7dee07b3aff3
Writing manifest to image destination
Storing signatures
Generating dockerfile with builder image registry.redhat.io/ubi8/php-80@sha256:484b11613bc0c2fb7acf2faf14f2c2ffd1f923e40a19dc211639124331b66567
Replaced Dockerfile FROM image registry.redhat.io/ubi8/php-80@sha256:484b11613bc0c2fb7acf2faf14f2c2ffd1f923e40a19dc211639124331b66567
Adding transient rw bind mount for /run/secrets/rhsm
[1/3] STEP 1/10: FROM registry.redhat.io/ubi8/php-80@sha256:484b11613bc0c2fb7acf2faf14f2c2ffd1f923e40a19dc211639124331b66567 AS appimageb3f13a8d3f6046c6992fad618df0f9d1
[1/3] STEP 2/10: LABEL "io.openshift.build.commit.message"="Merge pull request #131 from dperaza4dustbit/remove_v1_duplicate"       "io.openshift.build.source-location"="https://github.com/sclorg/cakephp-ex.git"       "io.openshift.build.image"="registry.redhat.io/ubi8/php-80@sha256:484b11613bc0c2fb7acf2faf14f2c2ffd1f923e40a19dc211639124331b66567"       "io.openshift.build.commit.author"="Petr Hracek <phracek@redhat.com>"       "io.openshift.build.commit.date"="Tue Apr 12 08:18:24 2022 +0200"       "io.openshift.build.commit.id"="69743d924a9bfeeee309590fc279f33430a9f009"       "io.openshift.build.commit.ref"="master"
[1/3] STEP 3/10: ENV OPENSHIFT_BUILD_NAME="cakephp-example-1"     OPENSHIFT_BUILD_NAMESPACE="rhscl-ci-testing"     OPENSHIFT_BUILD_SOURCE="https://github.com/sclorg/cakephp-ex.git"     OPENSHIFT_BUILD_COMMIT="69743d924a9bfeeee309590fc279f33430a9f009"     COMPOSER_MIRROR=""
[1/3] STEP 4/10: USER root
[1/3] STEP 5/10: COPY upload/scripts /tmp/scripts
[1/3] STEP 6/10: COPY upload/src /tmp/src
[1/3] STEP 7/10: RUN chown -R 1001:0 /tmp/scripts /tmp/src
[1/3] STEP 8/10: USER 1001
[1/3] STEP 9/10: RUN /tmp/scripts/assemble
---> Installing application source...
Found 'composer.json', installing dependencies using composer.phar...
Downloading https://getcomposer.org/installer, attempt 1/6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 58140  100 58140    0     0   267k      0 --:--:-- --:--:-- --:--:--  267k
By default, latest composer will be used. If you want to use v1 please use the environment variable COMPOSER_VERSION=1
All settings correct for using Composer
Downloading...

Composer (version 2.5.4) successfully installed to: /opt/app-root/src/composer.phar
Use it: php composer.phar

Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 80 installs, 0 updates, 0 removals
  - Downloading cakephp/plugin-installer (1.3.0)
  - Downloading aura/intl (3.0.0)
  - Downloading symfony/polyfill-ctype (v1.20.0)
  - Downloading twig/twig (v1.43.1)
  - Downloading umpirsky/twig-php-function (v0.1)
  - Downloading jasny/twig-extensions (v1.2.0)
  - Downloading psr/simple-cache (1.0.1)
  - Downloading psr/log (1.1.3)
  - Downloading paragonie/random_compat (v9.99.99)
  - Downloading psr/http-message (1.0.1)
  - Downloading laminas/laminas-zendframework-bridge (1.1.1)
  - Downloading laminas/laminas-diactoros (1.8.7p2)
  - Downloading cakephp/chronos (1.3.0)
  - Downloading cakephp/cakephp (3.9.3)
  - Downloading asm89/twig-cache-extension (1.4.0)
  - Downloading aptoma/twig-markdown (2.0.0)
  - Downloading ajgl/breakpoint-twig-extension (0.3.4)
  - Downloading wyrihaximus/twig-view (4.3.8)
  - Downloading cakephp/bake (1.12.0)
  - Downloading squizlabs/php_codesniffer (3.5.8)
  - Downloading cakephp/cakephp-codesniffer (3.3.0)
  - Downloading jdorn/sql-formatter (v1.2.17)
  - Downloading symfony/process (v4.4.15)
  - Downloading symfony/finder (v4.4.15)
  - Downloading symfony/filesystem (v4.4.15)
  - Downloading psr/container (1.0.0)
  - Downloading symfony/service-contracts (v1.1.9)
  - Downloading symfony/polyfill-php80 (v1.20.0)
  - Downloading symfony/polyfill-php73 (v1.20.0)
  - Downloading symfony/polyfill-mbstring (v1.20.0)
  - Downloading symfony/console (v4.4.15)
  - Downloading seld/phar-utils (1.1.1)
  - Downloading seld/jsonlint (1.8.2)
  - Downloading justinrainbow/json-schema (5.2.10)
  - Downloading composer/xdebug-handler (1.4.4)
  - Downloading composer/spdx-licenses (1.5.4)
  - Downloading composer/semver (1.7.1)
  - Downloading composer/ca-bundle (1.2.8)
  - Downloading composer/composer (1.10.16)
  - Downloading cakephp/debug_kit (3.22.4)
  - Downloading symfony/yaml (v4.4.15)
  - Downloading symfony/config (v4.4.15)
  - Downloading robmorgan/phinx (0.11.7)
  - Downloading cakephp/migrations (2.4.2)
  - Downloading m1/env (2.2.0)
  - Downloading josegonzalez/dotenv (3.2.0)
  - Downloading mobiledetect/mobiledetectlib (2.8.34)
  - Downloading webmozart/assert (1.9.1)
  - Downloading phpdocumentor/reflection-common (2.2.0)
  - Downloading phpdocumentor/type-resolver (1.4.0)
  - Downloading phpdocumentor/reflection-docblock (5.2.2)
  - Downloading phpunit/php-token-stream (2.0.2)
  - Downloading sebastian/version (2.0.1)
  - Downloading sebastian/resource-operations (1.0.0)
  - Downloading sebastian/recursion-context (3.0.0)
  - Downloading sebastian/object-reflector (1.1.1)
  - Downloading sebastian/object-enumerator (3.0.3)
  - Downloading sebastian/global-state (2.0.0)
  - Downloading sebastian/exporter (3.1.2)
  - Downloading sebastian/environment (3.1.0)
  - Downloading sebastian/diff (2.0.1)
  - Downloading sebastian/comparator (2.1.3)
  - Downloading phpunit/php-text-template (1.2.1)
  - Downloading doctrine/instantiator (1.3.1)
  - Downloading phpunit/phpunit-mock-objects (5.0.10)
  - Downloading phpunit/php-timer (1.0.9)
  - Downloading phpunit/php-file-iterator (1.4.5)
  - Downloading theseer/tokenizer (1.2.0)
  - Downloading sebastian/code-unit-reverse-lookup (1.0.1)
  - Downloading phpunit/php-code-coverage (5.3.2)
  - Downloading phpspec/prophecy (v1.10.3)
  - Downloading phar-io/version (1.0.1)
  - Downloading phar-io/manifest (1.0.1)
  - Downloading myclabs/deep-copy (1.10.1)
  - Downloading phpunit/phpunit (6.5.14)
  - Downloading symfony/polyfill-php72 (v1.20.0)
  - Downloading symfony/var-dumper (v4.4.15)
  - Downloading nikic/php-parser (v4.10.2)
  - Downloading dnoegel/php-xdg-base-dir (v0.1.1)
  - Downloading psy/psysh (v0.10.4)
For additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins
This warning will become an exception once you run composer update!
  - Installing cakephp/plugin-installer (1.3.0): Extracting archive
  - Installing aura/intl (3.0.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.20.0): Extracting archive
  - Installing twig/twig (v1.43.1): Extracting archive
  - Installing umpirsky/twig-php-function (v0.1): Extracting archive
  - Installing jasny/twig-extensions (v1.2.0): Extracting archive
  - Installing psr/simple-cache (1.0.1): Extracting archive
  - Installing psr/log (1.1.3): Extracting archive
  - Installing paragonie/random_compat (v9.99.99): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing laminas/laminas-zendframework-bridge (1.1.1): Extracting archive
  - Installing laminas/laminas-diactoros (1.8.7p2): Extracting archive
  - Installing cakephp/chronos (1.3.0): Extracting archive
  - Installing cakephp/cakephp (3.9.3): Extracting archive
  - Installing asm89/twig-cache-extension (1.4.0): Extracting archive
  - Installing aptoma/twig-markdown (2.0.0): Extracting archive
  - Installing ajgl/breakpoint-twig-extension (0.3.4): Extracting archive
  - Installing wyrihaximus/twig-view (4.3.8): Extracting archive
  - Installing cakephp/bake (1.12.0): Extracting archive
  - Installing squizlabs/php_codesniffer (3.5.8): Extracting archive
  - Installing cakephp/cakephp-codesniffer (3.3.0): Extracting archive
  - Installing jdorn/sql-formatter (v1.2.17): Extracting archive
  - Installing symfony/process (v4.4.15): Extracting archive
  - Installing symfony/finder (v4.4.15): Extracting archive
  - Installing symfony/filesystem (v4.4.15): Extracting archive
  - Installing psr/container (1.0.0): Extracting archive
  - Installing symfony/service-contracts (v1.1.9): Extracting archive
  - Installing symfony/polyfill-php80 (v1.20.0): Extracting archive
  - Installing symfony/polyfill-php73 (v1.20.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.20.0): Extracting archive
  - Installing symfony/console (v4.4.15): Extracting archive
  - Installing seld/phar-utils (1.1.1): Extracting archive
  - Installing seld/jsonlint (1.8.2): Extracting archive
  - Installing justinrainbow/json-schema (5.2.10): Extracting archive
  - Installing composer/xdebug-handler (1.4.4): Extracting archive
  - Installing composer/spdx-licenses (1.5.4): Extracting archive
  - Installing composer/semver (1.7.1): Extracting archive
  - Installing composer/ca-bundle (1.2.8): Extracting archive
  - Installing composer/composer (1.10.16): Extracting archive
  - Installing cakephp/debug_kit (3.22.4): Extracting archive
  - Installing symfony/yaml (v4.4.15): Extracting archive
  - Installing symfony/config (v4.4.15): Extracting archive
  - Installing robmorgan/phinx (0.11.7): Extracting archive
  - Installing cakephp/migrations (2.4.2): Extracting archive
  - Installing m1/env (2.2.0): Extracting archive
  - Installing josegonzalez/dotenv (3.2.0): Extracting archive
  - Installing mobiledetect/mobiledetectlib (2.8.34): Extracting archive
  - Installing webmozart/assert (1.9.1): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.4.0): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.2.2): Extracting archive
  - Installing phpunit/php-token-stream (2.0.2): Extracting archive
  - Installing sebastian/version (2.0.1): Extracting archive
  - Installing sebastian/resource-operations (1.0.0): Extracting archive
  - Installing sebastian/recursion-context (3.0.0): Extracting archive
  - Installing sebastian/object-reflector (1.1.1): Extracting archive
  - Installing sebastian/object-enumerator (3.0.3): Extracting archive
  - Installing sebastian/global-state (2.0.0): Extracting archive
  - Installing sebastian/exporter (3.1.2): Extracting archive
  - Installing sebastian/environment (3.1.0): Extracting archive
  - Installing sebastian/diff (2.0.1): Extracting archive
  - Installing sebastian/comparator (2.1.3): Extracting archive
  - Installing phpunit/php-text-template (1.2.1): Extracting archive
  - Installing doctrine/instantiator (1.3.1): Extracting archive
  - Installing phpunit/phpunit-mock-objects (5.0.10): Extracting archive
  - Installing phpunit/php-timer (1.0.9): Extracting archive
  - Installing phpunit/php-file-iterator (1.4.5): Extracting archive
  - Installing theseer/tokenizer (1.2.0): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Extracting archive
  - Installing phpunit/php-code-coverage (5.3.2): Extracting archive
  - Installing phpspec/prophecy (v1.10.3): Extracting archive
  - Installing phar-io/version (1.0.1): Extracting archive
  - Installing phar-io/manifest (1.0.1): Extracting archive
  - Installing myclabs/deep-copy (1.10.1): Extracting archive
  - Installing phpunit/phpunit (6.5.14): Extracting archive
  - Installing symfony/polyfill-php72 (v1.20.0): Extracting archive
  - Installing symfony/var-dumper (v4.4.15): Extracting archive
  - Installing nikic/php-parser (v4.10.2): Extracting archive
  - Installing dnoegel/php-xdg-base-dir (v0.1.1): Extracting archive
  - Installing psy/psysh (v0.10.4): Extracting archive
Package asm89/twig-cache-extension is abandoned, you should avoid using it. Use twig/cache-extension instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
24 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> App\Console\Installer::postInstall
Created `/opt/app-root/src/tmp` directory
Created `/opt/app-root/src/tmp/cache` directory
Created `/opt/app-root/src/tmp/cache/models` directory
Created `/opt/app-root/src/tmp/cache/persistent` directory
Created `/opt/app-root/src/tmp/cache/views` directory
Created `/opt/app-root/src/tmp/sessions` directory
Created `/opt/app-root/src/tmp/tests` directory
Permissions set on /opt/app-root/src/tmp/cache
Permissions set on /opt/app-root/src/tmp/cache/models
Permissions set on /opt/app-root/src/tmp/cache/persistent
Permissions set on /opt/app-root/src/tmp/cache/views
Permissions set on /opt/app-root/src/tmp/sessions
Permissions set on /opt/app-root/src/tmp/tests
Permissions set on /opt/app-root/src/tmp
Permissions set on /opt/app-root/src/logs
No Security.salt placeholder to replace.
=> sourcing 20-copy-config.sh ...
---> 13:19:47     Processing additional arbitrary httpd configuration provided by s2i ...
=> sourcing 00-documentroot.conf ...
=> sourcing 50-mpm-tuning.conf ...
=> sourcing 40-ssl-certs.sh ...
[1/3] STEP 10/10: CMD /usr/libexec/s2i/run
Getting image source signatures
Copying blob sha256:4ab945fc3fa986b14b14d286b8929debfbfdb187af674e7288cff3d324f75985
Copying blob sha256:5de674694847d50eaf5b5c7abd123782f093deafb481e0b54f48daa1532486cb
Copying blob sha256:8c2b45a30cdec517eab64cae63d412af4a809c9eda125e663a4e9b4706d5f593
Copying blob sha256:fb66af98d666ea380e373fb4aeca18a61af8a4da170afd998ef34cc17ad33cf7
Copying blob sha256:1b5ba87c4c8948c197b9d166046e0013de1023fdd2ea90efe27f0f647aa8ed0e
Copying config sha256:2ed190b15f567f8b9e5aed1d517ce05b3418cd60aa66225c493ecc2fc8ca8990
Writing manifest to image destination
Storing signatures
--> 2ed190b15f5
[3/3] STEP 1/1: FROM 2ed190b15f567f8b9e5aed1d517ce05b3418cd60aa66225c493ecc2fc8ca8990
[3/3] COMMIT temp.builder.openshift.io/rhscl-ci-testing/cakephp-example-1:1986f7b0
--> 2ed190b15f5
[2/3] STEP 1/2: FROM 2ed190b15f567f8b9e5aed1d517ce05b3418cd60aa66225c493ecc2fc8ca8990
[2/3] STEP 2/2: RUN /bin/sh -ic './vendor/bin/phpunit'
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in /opt/app-root/src/vendor/phpunit/phpunit/src/Util/Configuration.php on line 176
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

.Deprecated Error: Method ReflectionParameter::isArray() is deprecated in [/opt/app-root/src/vendor/phpunit/phpunit-mock-objects/src/Generator.php, line 1091]

Deprecated Error: Method ReflectionParameter::isCallable() is deprecated in [/opt/app-root/src/vendor/phpunit/phpunit-mock-objects/src/Generator.php, line 1093]

Deprecated Error: Method ReflectionParameter::getClass() is deprecated in [/opt/app-root/src/vendor/phpunit/phpunit-mock-objects/src/Generator.php, line 1097]

F......                                                            8 / 8 (100%)

Time: 174 ms, Memory: 8.00MB

There was 1 failure:

1) App\Test\TestCase\ApplicationTest::testBootstrapPluginWithoutHalt
Failed asserting that exception of type "ParseError" matches expected exception "InvalidArgumentException". Message was: "syntax error, unexpected token "match", expecting variable" at
/opt/app-root/src/tests/TestCase/ApplicationTest.php:65
/opt/app-root/src/vendor/phpunit/phpunit/phpunit:53
.

/opt/app-root/src/vendor/phpunit/phpunit/phpunit:53

FAILURES!
Tests: 8, Assertions: 21, Failures: 1.
error: build error: error building at STEP "RUN /bin/sh -ic './vendor/bin/phpunit'": error while running runtime: exit status 1
```

### PR DESCRIPTION
**Pull request by cuppett**
Resolves #136 

Have cleaned up this template for a few different things:

1. Removed everything.
2. Put back a fresh CakePHP 4.5
3. Minimum support raised to PHP 7.4 for current OCP versions (and CakePHP 4.5)
4. Put back OpenShift template and S2I needed files

The major steps taken can be seen in the separate commits in this PR.

Changes:

I had to add some new stanzas to the DeploymentConfigs on the mysql variants. The new PSA enforcement things were holding it up.

I  got rid of the intrusive alterations to the application views and layouts of the standard new-app generation that CakePHP does. This should make it more familiar to users of vanilla CakePHP, not encourage the incorrect database access pattern in the view and only highlight the material differences for S2I. This is most noticeable in the new default homepage:

image

(This used to have a lot of OpenShift badging and a little database counter.)

Tested on OCP 4.14.1 with UBI8-7.4, UBI8-8.0 and UBI9-8.0

### CODE REVIEW

**Comment by cuppett** [comment]
Holding at CakePHP 4.5 here because it supports 7.4+. 

CakePHP 5.x requires PHP 8.1+ (https://book.cakephp.org/5/en/installation.html)

**Comment by cuppett** [comment]
Another change that may be required in the future is a migration off of DeploymentConfig (no removal timeline presently):

image

**Comment by cuppett** [comment]
/hold 

I figured out the issue with UBI9. That PHP isn't honoring/receiving the environment variables from the container runtime. I'll play with that for a minute.

Also, the environment variables used in the same is a little bit complex. I think this is vestigial when we had postgres and mysql variants. Can be simplified for MySQL and I'll do that here.

**Comment by cuppett** [comment]
/hold cancel

I was able to identify the difference (using FPM) and where the behavior change came in:

https://github.com/sclorg/s2i-php-container/blob/ca8d3eba0fd3a924fd2be88c3e7d60d8888fd3c7/8.0/s2i/bin/run#L59-L74

This now works for UBI9 images and is ready for review.

**Comment by cuppett** [comment]
Verified this morning it works with UBI9 and PHP 8.1 also. We get an extra deprecation note (that I'd expect CakePHP 5 addresses, but doesn't cause us issues here):

image

**Comment by phracek** [comment]
> Another change that may be required in the future is a migration off of DeploymentConfig (no removal timeline presently):
> 
> image

As imagestreams as templates will be migrated soon to Helm Charts so Deployment will be used instead of. Thanks

**Comment by phracek** [comment]
Everything LGTM. Thanks

**Comment by phracek** [comment]
I would prefer to merge it and fix later on issues separately.

**Pull request merged**
