### PR TITLE
Upgrade to CakePHP 3.5.14 and layout from cakephp-app quickstart

### PR DESCRIPTION
**Pull request by cuppett**
1) Adopted the standard CakePHP app layout
   2) Divided up the sample content between layout
   3) Pinned a couple dependencies at PHP 7.0 compatible versions

### CODE REVIEW

**Comment by bparees** [comment]
@hhorak @pkubatrh ptal

**Comment by hhorak** [comment]
I guess this is a candidate for testing the staging branch (something we talked about when discussing how to not break things when changes in example applications are done). @pvalena, can you look at it, please?

**Comment by cuppett** [comment]
There is a known (non-blocking) break in origin, I have a chaser PR there: 

https://github.com/openshift/origin/pull/19110

**Comment by hhorak** [comment]
I've tested this manually with released images and it works fine, so merging.

**Pull request merged**
